const wordList = [
  {
    word: "approach",
    answer: [
      "다가가다[오다]",
      "(특히 부탁·제안 등을 하기 위해) 접촉하다, (다가가서) 말을 하다",
      "접근법, 처리 방법",
    ],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-11-26",
    wrongcount: 0,
  },
  {
    word: "construct",
    answer: ["건설하다", "구축하다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-01",
    wrongcount: 0,
  },
  {
    word: "demonstrate",
    answer: ["증명하다", "시위하다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-02",
    wrongcount: 0,
  },
  {
    word: "evaluate",
    answer: ["평가하다", "가치를 매기다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-03",
    wrongcount: 0,
  },
  {
    word: "feature",
    answer: ["특징", "특색", "주요 부분이 되다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "generate",
    answer: ["발생시키다", "생성하다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "hypothesis",
    answer: ["가설", "추측"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "implement",
    answer: ["구현하다", "실행하다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "justify",
    answer: ["정당화하다", "옹호하다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-08",
    wrongcount: 0,
  },
  {
    word: "knowledge",
    answer: ["지식", "앎"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "locate",
    answer: ["위치시키다", "찾아내다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "blithe",
    answer: ["즐거운"],
    options: ["걱정하는", "즐거운", "무관심한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "candid",
    answer: ["솔직한"],
    options: ["솔직한", "거친", "싸늘한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "dilapidated",
    answer: ["황폐한"],
    options: ["신선한", "황폐한", "부유한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "ephemeral",
    answer: ["일시적인"],
    options: ["영속적인", "일시적인", "영원한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "facetious",
    answer: ["농담적인"],
    options: ["진지한", "농담적인", "무심한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "gregarious",
    answer: ["교제를 즐기는"],
    options: ["포용적인", "교제를 즐기는", "고립된"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "haphazard",
    answer: ["무작위의"],
    options: ["무작위의", "조직적인", "계획적인"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "inevitable",
    answer: ["불가피한"],
    options: ["회피 가능한", "불가피한", "의심스러운"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "juxtapose",
    answer: ["병치하다"],
    options: ["분리하다", "병치하다", "합치다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "mellifluous",
    answer: ["달콤한"],
    options: ["고요한", "단조로운", "달콤한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "noxious",
    answer: ["해로운"],
    options: ["해독성 있는", "유용한", "해로운"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "obfuscate",
    answer: ["어렵게 만들다"],
    options: ["명확히 하다", "어렵게 만들다", "간단하게 하다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "quixotic",
    answer: ["이상주의적인"],
    options: ["이성적인", "이상주의적인", "냉정한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-04",
    wrongcount: 0,
  },
  {
    word: "paradox",
    answer: ["역설", "모순"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "quaint",
    answer: ["이색적인", "옛스러운"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "resilient",
    answer: ["회복력 있는", "탄력적인"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "tangible",
    answer: ["실체 있는", "만질 수 있는"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "ubiquitous",
    answer: ["어디에나 있는", "편재하는"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "venerate",
    answer: ["존경하다", "경배하다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "whimsical",
    answer: ["기발한", "변덕스러운"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "xenophile",
    answer: ["외국 문화 애호가"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "youthful",
    answer: ["젊은", "청년의"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "zealous",
    answer: ["열정적인", "열심인"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "articulate",
    answer: ["명확하게 표현하다", "분명한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "benevolent",
    answer: ["자비로운", "호의적인"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "concise",
    answer: ["간결한", "짧고 명료한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "diligent",
    answer: ["근면한", "성실한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "elusive",
    answer: ["이해하기 어려운", "잡기 어려운"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "fervent",
    answer: ["열렬한", "뜨거운"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "gregarious",
    answer: ["사교적인", "군집성의"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "hinder",
    answer: ["방해하다", "저해하다"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "innovative",
    answer: ["혁신적인", "창의적인"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  {
    word: "jovial",
    answer: ["유쾌한", "명랑한"],
    learncount: 0,
    reviewcount: 0,
    learndate: "2023-11-25",
    nextreview: "2023-12-05",
    wrongcount: 0,
  },
  // 추가 단어들...
];

export default wordList;
